print('what year where you born?')
born=input()
born=int(born)
print('what year do you want to know how old you would be from?')
year=input()
print('you would be')
print(year-born)
    
print('* '*6)
print('I '*6)
print('_'*11)
print('='*11)
print('='*11)
print('='*11)
print('_'*11)
print('BIRTHDAY!!!')
